theme: minima

title: Portafolio de OFranciscoDev
author: Oscar Eduardo Ramírez Aguilar
description: >-
  Estudiante de Ingeniería en Ciencias de la Computación, interesado en
  desarrollo de software, bases de datos, ciberseguridad y nuevas tecnologías.

github_username: OFranciscoDev
show_excerpts: true
